import { HeaderPhoto } from '@/lib/landing-types';

export const headerPhotos: HeaderPhoto[] = [
  {
    src: '/cursor-event-01.jpg',
    alt: 'Cursor Calgary meetup',
    row: 1,
    col: 1,
    rowSpan: 2,
    colSpan: 2,
    mobile: { row: 1, col: 1, rowSpan: 2, colSpan: 2 },
  },
  {
    src: '/cursor-event-02.jpg',
    alt: 'Coding session at Cursor Calgary',
    row: 1,
    col: 3,
    mobile: { row: 3, col: 1 },
  },
  {
    src: '/cursor-event-03.jpg',
    alt: 'Community at Cursor Calgary',
    row: 1,
    col: 4,
    rowSpan: 2,
    mobileHidden: true,
  },
  {
    src: '/cursor-event-04.jpg',
    alt: 'Collaboration at Cursor Calgary',
    row: 2,
    col: 3,
    mobile: { row: 3, col: 2 },
  },
  {
    src: '/cursor-event-05.jpg',
    alt: 'Building with Cursor',
    row: 3,
    col: 1,
    rowSpan: 2,
    mobileHidden: true,
  },
  {
    src: '/cursor-event-06.jpg',
    alt: 'Cursor Calgary event',
    row: 3,
    col: 2,
    rowSpan: 2,
    colSpan: 2,
    mobileHidden: true,
  },
  {
    src: '/cursor-event-07.jpg',
    alt: 'Cursor Calgary attendees',
    row: 3,
    col: 4,
    rowSpan: 2,
    mobile: { row: 4, col: 1, colSpan: 2 },
  },
];
