import { HeaderPhoto } from '@/lib/landing-types';

export const headerPhotos: HeaderPhoto[] = [
  {
    src: '/event-venue-wide.jpg',
    alt: 'Cursor Hackathon UCalgary venue',
    row: 1,
    col: 1,
    rowSpan: 2,
    colSpan: 2,
    mobile: { row: 1, col: 1, rowSpan: 2, colSpan: 2 },
  },
  {
    src: '/event-winners-1st.jpg',
    alt: '1st place winners at Cursor Hackathon',
    row: 1,
    col: 3,
    mobile: { row: 3, col: 1 },
  },
  {
    src: '/event-hacking.jpg',
    alt: 'Teams hacking at Cursor Hackathon',
    row: 1,
    col: 4,
    rowSpan: 2,
    mobileHidden: true,
  },
  {
    src: '/event-demos.jpg',
    alt: 'Demo presentations at Cursor Hackathon',
    row: 2,
    col: 3,
    mobile: { row: 3, col: 2 },
  },
  {
    src: '/event-coding.jpg',
    alt: 'Participants coding at Cursor Hackathon',
    row: 3,
    col: 1,
    rowSpan: 2,
    mobileHidden: true,
  },
  {
    src: '/event-crowd.jpg',
    alt: 'Crowd at Cursor Hackathon UCalgary',
    row: 3,
    col: 2,
    rowSpan: 2,
    colSpan: 2,
    mobileHidden: true,
  },
  {
    src: '/event-networking.jpg',
    alt: 'Networking at Cursor Hackathon',
    row: 3,
    col: 4,
    rowSpan: 2,
    mobile: { row: 4, col: 1, colSpan: 2 },
  },
];
